steps:
- name: 'gcr.io/cloud-builders/gsutil'
  entrypoint: 'bash'
  dir: mapping_configs
  args:
  - '-c'
  - |
    find ./ -type f -exec sed -i -e 's/\$$MAPPING_ENGINE_HOME/gs:\/\/$_MAPPING_BUCKET\/$_MAPPING_ROOT_FOLDER/g' {} \;
- name: 'gcr.io/cloud-builders/gsutil'
  entrypoint: 'bash'
  dir: mapping_configs
  args:
  - '-c'
  - |
    gsutil cp README.md gs://$_MAPPING_BUCKET/$_MAPPING_ROOT_FOLDER/mapping_configs
- name: 'gcr.io/cloud-builders/gsutil'
  entrypoint: 'bash'
  dir: mapping_configs
  args:
  - '-c'
  - |
    find ./ -type f -exec sed -i -e 's/local_path/gcs_location/g' {} \;
- name: 'gcr.io/cloud-builders/gsutil'
  entrypoint: 'bash'
  dir: mapping_configs
  args:
  - '-c'
  - |
    gsutil rm -r gs://$_MAPPING_BUCKET/$_MAPPING_ROOT_FOLDER/mapping_configs
- name: 'gcr.io/cloud-builders/gsutil'
  entrypoint: 'bash'
  dir: mapping_configs
  args:
  - '-c'
  - |
    gsutil cp -r * gs://$_MAPPING_BUCKET/$_MAPPING_ROOT_FOLDER/mapping_configs

options:
  logging: CLOUD_LOGGING_ONLY